{% set name = "datastock" %}
{% set version = "0.0.14" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/datastock-{{ version }}.tar.gz
  sha256: 8afdc6b323a3e8d5a1cce4f1ebf1c78ec9e4cfd06dbc444ae1fa91c44c0b58b0

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - matplotlib-base
    - numpy
    - python >=3.6
    - scipy

test:
  imports:
    - datastock
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ToFuProject/datastock
  summary: A python library for generic class and data handling
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Didou09
